name: Advent of Code Solution

on:
  workflow_dispatch:
    inputs:
      day:
        description: 'Day of Advent of Code (1-25)'
        required: true
        default: '1'
      input_type:
        description: 'Input type (test/actual)'
        required: true
        default: 'test'

env:
  AOC_YEAR: 2024
  AOC_SESSION: ${{ secrets.AOC_SESSION_COOKIE }}

jobs:
  solve:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set Day
      id: set-day
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          DAY="${{ github.event.inputs.day }}"
        else
          # Extract day from changed file path
          DAY=$(echo "$filepath" | sed -E 's/.*day([0-9]+).*/\1/')
        fi
        
        # Pad single-digit days with zero
        FORMATTED_DAY=$(printf "%02d" $DAY)
        echo "day=$FORMATTED_DAY" >> $GITHUB_OUTPUT
    
    - name: Determine Input Type
      id: input-type
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "type=test" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "type=${{ github.event.inputs.input_type }}" >> $GITHUB_OUTPUT
        else
          echo "type=actual" >> $GITHUB_OUTPUT
        fi
    
    - name: Fetch Puzzle Input
      env:
        AOC_INPUT_TYPE: ${{ steps.input-type.outputs.type }}
        AOC_DAY: ${{ steps.set-day.outputs.day }}
      run: |
        # Create day directory if not exists
        mkdir -p day$AOC_DAY
        
        if [[ "$AOC_INPUT_TYPE" == "test" ]]; then
          # For test input, you can manually add or generate it
          echo "Test input placeholder for Day $AOC_DAY" > day$AOC_DAY/input.txt
        else
          # Fetch actual puzzle input
          curl -s 'https://adventofcode.com/'$AOC_YEAR'/day/'$(echo $AOC_DAY | sed 's/^0*//')/input \
            --cookie "session=$AOC_SESSION" \
            > day$AOC_DAY/input.txt
        fi
    
    - name: Install SQLite
      run: sudo apt-get update && sudo apt-get install -y sqlite3

    - name: Debug Workflow Context
      env:
        AOC_DAY: ${{ steps.set-day.outputs.day }}
      run: |
        echo "Working directory: $(pwd)"
        echo "Day directory contents:"
        ls -la day$AOC_DAY
        cat day$AOC_DAY/input.txt
        cat day$AOC_DAY/solve.sql || echo "solve.sql not found"

    - name: Create SQLite Database and Input Table
      env:
        AOC_DAY: ${{ steps.set-day.outputs.day }}
      run: |
        cd day$AOC_DAY

        echo "Creating input table." > run_log.txt

        sqlite3 solution.db <<EOF
        CREATE TABLE input (value TEXT);
        .quit
        EOF

    - name: Import Input Data
      env:
        AOC_DAY: ${{ steps.set-day.outputs.day }}
      run: |
        cd day$AOC_DAY

        echo "Importing input." >> run_log.txt
        cat input.txt >> run_log.txt

        sqlite3 solution.db < <(echo ".import input.txt input")
    
    - name: Solve Advent of Code Challenge
      env:
        AOC_INPUT_TYPE: ${{ steps.input-type.outputs.type }}
        AOC_DAY: ${{ steps.set-day.outputs.day }}
      run: |
        cd day$AOC_DAY

        echo "Running solve.sql against solution.db" >> run_log.txt
        
        echo "Running sqlite"
        sqlite3 solution.db < solve.sql >> run_log.txt 2>&1
        
        cat run_log.txt
    
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: day${{ steps.set-day.outputs.day }}-${{ steps.input-type.outputs.type }}-results
        path: day${{ steps.set-day.outputs.day }}/run_log.txt
